### ISSUE TITLE
Keep getting Error in Logs 

### ISSUE THREAD

**Issue by thorrrr** [HandyHat/ha-hildebrandglow-dcc#117]
This is a constant error i get on every reboot of HA.

<html>
<body>

Version | core-2021.12.9
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.88
CPU Architecture | x86_64
Timezone | Europe/London

</body>
</html>
Glow API data error (Electric Tariff Rate): (list index out of range)
09:48:31 – (ERROR) Hildebrand Glow (DCC) (custom integration) - message first occurred at 09:48:31 and shows up 2 times
Glow API data error (Electric Tariff Standing): (list index out of range)
09:46:31 – (ERROR) Hildebrand Glow (DCC) (custom integration) - message first occurred at 09:46:31 and shows up 2 times

**Comment by ColinRobbins** [comment]
This error indicates the Glow API is behaving differently for you in some way.

Can you perhaps edit the file `custom_intergtaion/ha-hildebrandglow-dcc/sensor.py` and change line 354 from
```
                _LOGGER.error("Glow API data error (%s): (%s)",
                              self.name, _error)
```
to
```
                _LOGGER.error("Glow API data error (%s): (%s : %s)",
                              self.name, _error, plan)
```
Then we should be able to see the cause.

**Comment by thorrrr** [comment]
HI

Is this the  error

Logger: homeassistant.config_entries
Source: loader.py:535
First occurred: 16:01:27 (1 occurrences)
Last logged: 16:01:27

Error setting up entry for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313,
in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File
"/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line
204, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py",
line 147, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 309, in
async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in
get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in
_import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in
_call_with_frames_removed
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 355
    self.name, _error plan)
                      ^
SyntaxError: invalid syntax

**Comment by ColinRobbins** [comment]
Looks like you have not quite got the edit right.
I think you have a comma missing between `_error` and `plan`.

**Comment by thorrrr** [comment]
Hi Colin
You were correct fixed new error

This error originated from a custom integration.

Logger: custom_components.hildebrandglow_dcc.sensor
Source: custom_components/hildebrandglow_dcc/sensor.py:278
Integration: Hildebrand Glow (DCC) (documentation, issues)
First occurred: 16:22:12 (2 occurrences)
Last logged: 16:22:12

Glow API data error (Electric Tariff Standing): (list index out of range)
Glow API data error (Gas Tariff Standing): (list index out of range)

**Comment by thorrrr** [comment]
Hi Colin
No errors now has this fixed it or have you just stopped it showing? :)

**Comment by ColinRobbins** [comment]
Good news.
The change will not have made any difference, it was attempting to get more data on the error.
I suspect that for some reason the Glow API was not supplying the tarrif data, which caused the error.
So my guess is whatever the problem was at the Glow end of the connection, it has been resolved.

**Comment by thorrrr** [comment]
HI 
I am still having issues with the integration reporting wrong prices on monthly / yearly  see [here](https://1drv.ms/u/s!Ao6WCX2miTCJjNIZZ6BKcw65WZEGuQ?e=dzpl8c)

I followed the directions from you docs

**Comment by ColinRobbins** [comment]
Sorry, I don't know what to advise.

This integration provides the raw data used by HA, by taking a reading at
regular points in time
The raw data appears correct for the current week as per your current
graphs.

In terms of Energy configuration - this is what I have...
[image: image.png]
Does yours look the same?

Other than that, sorry no idea why HA is showing the incorrect
monthly aggregated value.
As I understand it the aggregated value is calculated on the fly by HA
adding the data points up.
So the only thing I can suggest it to look into the database directly and
see if there is a rogue data point of some sort.

**Comment by thorrrr** [comment]
THIsis my settings see [here](https://1drv.ms/u/s!Ao6WCX2miTCJjNIaMg87rE036i3UBw?e=SxD2kG)

**Comment by ColinRobbins** [comment]
That all looks OK.
I can only think it is a rogue data point somewhere.

**Comment by thorrrr** [comment]
HI Colin
How can i check for that ?

**Comment by ColinRobbins** [comment]
There not really an easy way in HA, and depends your SQL knowledge.
If you are happy with SQL, you could use SQLLite to query the HA database and see what is stored in the stats tables for energy.
If you see a rogue value, change/delete it.
I did it once myself over a few evenings to debug a different issue, by looking at the code behind the energy dashboard to see what tables it was using, and had a look at the databse directly.  But not really sure I could talk you through it.

Do you need *ANY* historic data in HA (All integrations, not jsut energy)?  
If not, you could delete the database and restart HA. 
The database is only used for recoridng stats, so you should not lose any configuraiton, but will lost all history data,   I've done it myself a few times in the past for various reasons.
Then you can see of the problem reoccurs over time.

Not idea, but I'm out of ideas - the integration appears to be giving correct data right now.

**Comment by ColinRobbins** [comment]
For hints on exploring the database see [this thead](https://community.home-assistant.io/t/energy-dashboard-allow-gas-as-kwh/339891/27).

**Comment by HandyHat** [comment]
@thorrrr Is this still an issue?

**Comment by thorrrr** [comment]
I just checked feed down again no readings after 7pm

**Comment by thorrrr** [comment]
Now its back to normal  :)
